<?xml version="1.0" encoding="utf-8"?><Database Name="assignmentdb" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ICS-LT-CZFBR73;Initial Catalog=assignmentdb;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="codebased6.Properties.Settings" SettingsPropertyName="assignmentdbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Code_Employes" Member="Code_Employes">
    <Type Name="Code_Employe">
      <Column Name="empno" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="empname" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="empsal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="emptype" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
</Database>